# Generated by Django 5.1.3 on 2024-12-12 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_guidancesession_action_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('address', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('civil_status', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('father_education', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_education', models.CharField(blank=True, max_length=255, null=True)),
                ('parents_marital_status', models.CharField(max_length=100)),
                ('elementary_school', models.CharField(max_length=255)),
                ('elementary_year_graduated', models.CharField(max_length=50)),
                ('high_school', models.CharField(max_length=255)),
                ('high_school_year_graduated', models.CharField(max_length=50)),
                ('college_school', models.CharField(blank=True, max_length=255, null=True)),
                ('college_course', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_for_interview', models.TextField()),
                ('presenting_problem', models.TextField()),
                ('background_of_problem', models.TextField()),
                ('counselor_notes', models.TextField(blank=True, null=True)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('follow_up_needed', models.BooleanField(default=False)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_interviews', to='core.counselor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_forms', to='core.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
