# Generated by Django 5.1.3 on 2024-12-13 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_interview'),
    ]

    operations = [
    ]
