# Generated by Django 4.2.7 on 2025-01-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('counselor', 'Counselor'), ('student', 'Student')], max_length=10),
        ),
    ]
