# Generated by Django 4.2.7 on 2025-01-05 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_systemsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SystemSettings',
        ),
    ]
